# -*- coding: utf-8 -*-
"""
=============================
周度总结报告生成器
=============================
每周六运行，总结本周（周一至周五）的交易数据和分析报告。
"""

from __future__ import annotations
import json, logging, os, sys, time
from datetime import datetime, timedelta
from pathlib import Path
import requests
import smtplib
from email.mime.text import MIMEText

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)-8s | %(message)s", datefmt="%H:%M:%S")
logger = logging.getLogger("weekly")

HHXG_BASE = "https://hhxg.top/api"
ANSPIRE_BASE = "https://open-gateway.anspire.cn/v6"


def get_trading_week_range() -> tuple:
    """计算本周一至周五的日期范围"""
    today = datetime.now()
    monday = today - timedelta(days=today.weekday())
    friday = monday + timedelta(days=4)
    return monday.strftime("%Y-%m-%d"), friday.strftime("%Y-%m-%d"), monday.strftime("%Y%m%d"), friday.strftime("%Y%m%d")


def fetch_weekly_market_data() -> dict:
    """从 hhxg API 获取当前市场数据作为周度总结的基点"""
    try:
        r = requests.get(f"{HHXG_BASE}/snapshot", timeout=30)
        r.raise_for_status()
        d = r.json()
        return d.get("data", {}) if d.get("success") else {}
    except Exception as e:
        logger.warning("hhxg API 不可用: %s", e)
        return {}


def fetch_calendar_events() -> list:
    """获取下周重要日历（解禁、财报等）"""
    try:
        r = requests.get(f"{HHXG_BASE}/calendar", timeout=30)
        r.raise_for_status()
        d = r.json()
        return d.get("data", {}).get("events", []) if d.get("success") else []
    except Exception:
        return []


def generate_llm_summary(week_data: dict, week_start: str, week_end: str, api_key: str) -> str:
    """使用LLM生成本周总结"""
    if not api_key:
        return None

    mkt = week_data.get("market", {})
    themes = week_data.get("hot_themes", [])
    ladder = week_data.get("ladder", {})
    ai_summary = week_data.get("ai_summary", {})

    theme_lines = "\n".join([
        f"  - {t.get('name', '')}: {t.get('limitup_count', 0)}只涨停"
        for t in themes[:8]
    ])

    prompt = f"""你是A股市场周度复盘分析师。基于以下本周最后一个交易日的数据，撰写本周总结。

【时间范围】{week_start} 至 {week_end}
【本周最后交易日情绪】赚钱效应 {mkt.get('sentiment_index', '?')}/100
【最高连板】{ladder.get('max_streak', '?')}板
【本周活跃题材】
{theme_lines}

请用Markdown格式写一份简洁的周度总结（500字以内）：
1. **本周市场回顾**：指数走势概要、情绪周期变化
2. **主线题材盘点**：本周哪2-3条主线表现最强、核心标的
3. **赚钱效应统计**：本周涨停数趋势、炸板率变化
4. **下周展望**：主线能否持续、需要关注的风险和新机会
5. **操作建议**：下周仓位策略和关注方向"""

    try:
        resp = requests.post(
            f"{ANSPIRE_BASE}/chat/completions",
            headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
            json={
                "model": "Doubao-Seed-2.0-lite",
                "messages": [
                    {"role": "system", "content": "你是A股复盘专家。简洁专业，Markdown格式。"},
                    {"role": "user", "content": prompt},
                ],
                "temperature": 0.4,
                "max_tokens": 2000,
            },
            timeout=120,
        )
        if resp.status_code == 200:
            return resp.json()["choices"][0]["message"]["content"]
    except Exception as e:
        logger.error("LLM失败: %s", e)
    return None


def build_weekly_report(week_data: dict, llm_summary: str, week_start: str, week_end: str) -> str:
    """生成周度报告"""
    mkt = week_data.get("market", {})
    themes = week_data.get("hot_themes", [])
    ladder = week_data.get("ladder", {})
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    lines = [
        f"# 📊 A股周度总结报告",
        f"**{week_start} ~ {week_end}** | 生成: {now}",
        "",
        "---",
    ]

    if llm_summary:
        lines += ["", "## 🧠 AI 周度综述", "", llm_summary, "", "---"]

    lines += [
        "",
        "## 📈 本周最后交易日市场数据",
        "",
        f"| 指标 | 数值 |",
        f"|------|------|",
        f"| 赚钱效应指数 | {mkt.get('sentiment_index', '?')}/100 |",
        f"| 市场情绪 | {mkt.get('sentiment_label', '?')} |",
        f"| 涨停家数 | {mkt.get('limit_up', '?')} |",
        f"| 炸板家数 | {mkt.get('fried', '?')} |",
        f"| 跌停家数 | {mkt.get('limit_down', '?')} |",
        f"| 最高连板 | {ladder.get('max_streak', '?')}板 |",
        "",
        "---",
        "",
        "## 🔥 本周主线题材",
        "",
        "| 题材 | 涨停数 | 核心标的 |",
        "|------|:---:|------|",
    ]
    for t in themes[:10]:
        tops = t.get("top_stocks", [])
        top_names = "/".join(s.get("name", "") for s in tops[:2])
        lines.append(f"| {t['name']} | {t.get('limitup_count', 0)} | {top_names} |")

    lines += [
        "",
        "---",
        "",
        "## ⚠️ 免责声明",
        "> 本报告基于公开市场数据和AI模型生成，仅供研究参考，不构成投资建议。",
        "",
        f"*Generated by DSA Weekly Reporter @ {now}*",
    ]

    return "\n".join(lines)


def send_email(report: str):
    sender = os.getenv("EMAIL_SENDER", "").strip()
    pwd = os.getenv("EMAIL_PASSWORD", "").strip()
    to = os.getenv("EMAIL_RECEIVERS", "").strip() or sender

    if not sender or not pwd:
        logger.warning("邮件配置不完整")
        return False

    domain = sender.split("@")[-1].lower()
    smtp_map = {"qq.com": ("smtp.qq.com", 465), "163.com": ("smtp.163.com", 465)}
    server_addr, port = smtp_map.get(domain, ("smtp.qq.com", 465))

    try:
        msg = MIMEText(report, "plain", "utf-8")
        week_label = datetime.now().strftime("%m/%d")
        msg["Subject"] = f"📊 A股周度总结报告 ({week_label})"
        msg["From"] = sender
        msg["To"] = to
        s = smtplib.SMTP_SSL(server_addr, port, timeout=30)
        s.login(sender, pwd)
        s.sendmail(sender, to.split(","), msg.as_string())
        s.quit()
        logger.info("✅ 周报已发送 → %s", to)
        return True
    except Exception as e:
        logger.error("邮件失败: %s", e)
        return False


def main():
    from dotenv import load_dotenv
    load_dotenv()
    api_key = os.getenv("ANSPIRE_API_KEYS", "").strip()

    week_start, week_end, _, _ = get_trading_week_range()
    print(f"📊 生成周度总结: {week_start} ~ {week_end}")

    week_data = fetch_weekly_market_data()
    calendar = fetch_calendar_events()

    llm_text = generate_llm_summary(week_data, week_start, week_end, api_key)
    report = build_weekly_report(week_data, llm_text, week_start, week_end)

    out_dir = Path("reports")
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"weekly_{week_start}_{week_end}.md"
    out_path.write_text(report, encoding="utf-8")
    print(f"✅ 报告: {out_path}")

    send_email(report)
    return report


if __name__ == "__main__":
    main()
